### ISSUE TITLE
Login with GitHub

### ISSUE THREAD

**Issue by 5ouma** [Basedash/dockhunt#11]
Since Twitter login is probably not going to be free, why don't you add a GitHub login option? I want it even if Twitter keeps it free.

**Comment by MaxMusing** [comment]
We're pretty tied to Twitter auth for now (we're using Twitter username as a unique identifier on users). Open to reconsidering depending on Twitter's future.

**Comment by Twipped** [comment]
@MaxMusing you uniqued on a value that the user can change at will and can be swapped between accounts? Why didn't you use the user id?

**Comment by MaxMusing** [comment]
Yeah, Twitter ID (or just a Dockhunt-specific UUID) as the user's PK would be better. Decided not to support this during initial development since repeat usage isn't super common. Would want to keep Twitter handle as a unique value to support pretty URLs though (e.g. `/users/MaxMusing`).

Open to PRs :)
